# Generated by Django 5.2 on 2025-05-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=6),
        ),
        migrations.AddField(
            model_name='book',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=29.99, max_digits=6),
        ),
    ]
